version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add other environment variables as needed
    networks:
      - app-network

  # Uncomment if you want to deploy the backend as well
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/buddyboard
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network
  
  # db:
  #   image: postgres:14
  #   restart: always
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=buddyboard
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# Uncomment if using database
# volumes:
#   postgres_data: 